### ISSUE TITLE
Can't find "pheatmap"

### ISSUE THREAD

**Issue by jkcooley** [raynamharris/R_Intro_for_Bioinformatics#2]
When running lines 91-end, I get this error:
"Error in library("pheatmap") : there is no package called ‘pheatmap’"

Is there something I should download before running this tutorial?

**Comment by raynamharris** [comment]
Thanks for the suggestion @jkcooley 
I've updated the code with a comment about this error.
https://github.com/raynamharris/R_Intro_for_Bioinformatics/commit/98449b9a3a9bf500c01d64f945e34e20b2a7b8d8
